version: 2
dependencies:
  cache_directories:
    - "vendor/apt"
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk8:jdk8u152-b16
    steps:
      - checkout
      - run:
          name: Install Os dependencies
          command: ./build/x86_64/linux_macos/osDependencies.sh
      - run:
          name: Build and install make via script
          command: ./build/x86_64/linux_macos/installMake.sh
      - run:
          environment:
            JAVA_VERSION: jdk8u152-b16
            JAVA_HOME: /opt/java/openjdk/${JAVA_VERSION}
          name: Build via the local build script
          command: ./build/x86_64/linux_macos/local-build.sh
