version: 2
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk8:jdk8u152-b16
    steps:
      - checkout
      - run:
          name: Build via the local build script
          command: ./build/x86_64/linux_macos/local-build.sh