version: 2
dependencies:
  cache_directories:
    - "vendor/apt"
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk8:jdk8u152-b16
    steps:
      - checkout
      - run:
          name: Install Os dependencies
          command: ./build/x86_64/linux_macos/osDependencies.sh
          timeout: 2m
      - run:
          name: Build and install make via script
          command: ./build/x86_64/linux_macos/installMake.sh
          timeout: 2m
      - run:
          name: Define Environment Variables and update JAVA_HOME and PATH at Runtime
          command: |
            echo 'export JAVA_VERSION=jdk8u144-b01'                   >> ${BASH_ENV}
            echo 'export JAVA_HOME=/opt/java/openjdk/${JAVA_VERSION}' >> ${BASH_ENV}
            echo 'export PATH=${JAVA_HOME}/bin:${PATH}'               >> ${BASH_ENV}
            source ${BASH_ENV}
      - run:
          name: Build via the local build script
          command: ./build/x86_64/linux_macos/local-build.sh
          timeout: 10m
          no_output_timeout: 5m
